movie_project/movie_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MovieListView.as_view(), name='all_movies'),
    path('movie/<slug:slug>', views.MovieDetailInfo.as_view(), name='movie_detail'),
    path('director/<slug:slug>', views.DirectorInfoView.as_view(), name='director_info'),
    path('directors', views.DirectorListView.as_view(), name='all_directors'),
    path('actors', views.ActorsListView.as_view(), name='all_actors'),
    path('actor/<slug:slug>', views.ActorInfoView.as_view(), name='actor_info'),
]

movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Админка'
admin.site.index_title = 'Моя админка'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('movie_app.urls')),
]

movie_project/movie_app/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField
from slugify import slugify

def instance_slug(instance):
    return instance.slug

def slugify_value(value:str):
    return value.replace(' ', '-')


class Actor(models.Model):
    MALE = 'M'
    FEMALE = 'F'

    GENDERS = [
        (MALE, 'Мужчина'),
        (FEMALE, 'Жещина')
    ]

    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    gender = models.CharField(choices=GENDERS, max_length=1, default=MALE, verbose_name='Пол')
    # slug = models.SlugField(blank=True, db_index=True, null=False, unique=True)
    slug = AutoSlugField('SLUG', max_length=100, db_index=True,
                         unique=True, populate_from=instance_slug, slugify=slugify_value)


    def __str__(self):
        if self.gender == self.MALE:
            return f'Актер {self.first_name} {self.last_name}'
        return f'Актриса {self.first_name} {self.last_name}'

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.first_name} {self.last_name}')
        super(Actor, self).save(*args, **kwargs)

    def get_url(self):
        return reverse('actor_info', args=(self.slug,))


class Director(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    email = models.EmailField(blank=True, verbose_name='Почта')
    slug = AutoSlugField('slug', max_length=100, db_index=True,
                         unique=True, populate_from=instance_slug, slugify=slugify_value)
    # slug = models.SlugField(null=False, db_index=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_url(self):
        return reverse('director_info', args=(self.slug,))

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.first_name} {self.last_name}')
        super(Director, self).save(*args, **kwargs)


class Movie(models.Model):
    EURO = 'EUR'
    USD = 'USD'
    RUB = 'RUB'
    CURRNECY_CHOICES = [
        (RUB, 'Rubles'),
        (USD, 'Dollars'),
        (EURO, 'Euro'),
    ]

    name = models.CharField(max_length=40, verbose_name='Название фильма')
    rating = models.IntegerField(validators=[MinValueValidator(1),
                                             MaxValueValidator(100)], verbose_name='Рейтинг')
    year = models.IntegerField(null=True, blank=True, verbose_name='Год')
    budget = models.IntegerField(default=1000000, validators=[MinValueValidator(1)], verbose_name='Бюджет')
    currency = models.CharField(max_length=3, choices=CURRNECY_CHOICES, default=RUB, verbose_name='Валюта')
    directors = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Режисер') #related_name - атрибут для изменения названия доступа к связным таблицам
    actors = models.ManyToManyField(Actor, blank=True, verbose_name='Актеры')
    # slug = models.SlugField(default='', null=False)
    slug = AutoSlugField('SLUG', max_length=100, db_index=True,
                         unique=True, populate_from=instance_slug, slugify=slugify_value)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Movie, self).save(*args, **kwargs)

    def get_url(self):
        return reverse('movie_detail', args=[self.slug])

    def __str__(self):
        return f"{self.name} - {self.rating}"

movie_project/movie_app/views.py
from django.db.models import Avg, Max, Min, Count, Value
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Movie, Director, Actor


# ---------- Movie CBV ----------
class MovieListView(ListView):
    template_name = 'movie_app/show_all_movie.html'
    model = Movie
    context_object_name = 'movies'

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     print(queryset)
    #     # agg = queryset.aggregate(Count('id'),
    #     #                            Avg('budget'),
    #     #                            Max('rating'),
    #     #                            Min('rating'),
    #     #                            )
    #     # queryset['agg'] = agg
    #     return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        agg = context['movies'].aggregate(Count('id'),
                                   Avg('budget'),
                                   Max('rating'),
                                   Min('rating'),
                                   )
        context['agg'] = agg
        return context

# def show_all_movie(request):
#     movies = Movie.objects.all()
#     movies = Movie.objects.annotate(new_field_bool=Value(True))
#     agg = movies.aggregate(Count('id'),
#                            Avg('budget'),
#                            Max('rating'),
#                            Min('rating'),
#                            )
#     context = {
#         'movies': movies,
#         'agg': agg,
#     }
#     return render(request, 'movie_app/show_all_movie.html', context=context)


class MovieDetailInfo(DetailView):
    template_name = 'movie_app/movie_info.html'
    model = Movie
    context_object_name = 'movie'


# def get_movie_info(request, slug_movie: str):
#     movie = get_object_or_404(Movie, slug=slug_movie)
#     context = {
#         'movie': movie,
#     }
#     return render(request, 'movie_app/movie_info.html', context=context)


# ---------- Movie CBV ----------

# ---------- Director CBV ----------
class DirectorListView(ListView):
    template_name = 'movie_app/directors.html'
    model = Director
    context_object_name = 'directors'


# def show_all_directors(request):
#     directors = Director.objects.all()
#     context = {
#         'directors': directors
#     }
#     return render(request, 'movie_app/directors.html', context=context)

class DirectorInfoView(DetailView):
    template_name = 'movie_app/director_info.html'
    model = Director
    context_object_name = 'director'


# def get_info_about_director(request, slug_director):
#     director = get_object_or_404(Director, slug=slug_director)
#     context = {
#         'director': director,
#     }
#     return render(request, 'movie_app/director_info.html', context=context)
# ---------- Director CBV ----------

# ---------- Actor CBV ----------
class ActorsListView(ListView):
    template_name = 'movie_app/actors.html'
    model = Actor
    context_object_name = 'actors'


# def show_all_actors(request):
#     actors = Actor.objects.all()
#     context = {
#         'actors': actors
#     }
#     return render(request, 'movie_app/actors.html', context=context)

class ActorInfoView(DetailView):
    template_name = 'movie_app/actor_info.html'
    model = Actor
    context_object_name = 'actor'

# def get_info_about_actor(request, slug_actor):
#     actor = get_object_or_404(Actor, slug=slug_actor)
#     context = {
#         'actor': actor,
#     }
#     return render(request, 'movie_app/actor_info.html', context=context)
# ---------- Actor CBV ----------

movie_project/movie_app/templates/includes/navbar.html
<nav>
    <a href="{% url 'all_movies' %}">Фильмы</a> |
    <a href="{% url 'all_actors' %}">Актеры</a> |
    <a href="{% url 'all_directors' %}">Режесеры</a> |
</nav>

movie_project/movie_app/templates/movie_app/actor_info.html
{% extends 'base.html' %}

{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'movie_app/css/detail_info.css' %}">
{% endblock %}

{% block title %}
    {{ actor }}
{% endblock %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <div class="info">
        <h2>Имя - {{ actor.first_name }}</h2>
        <h2>Фамилия - {{ actor.last_name }}</h2>
        <h2>Пол - {{ actor.gender }}</h2>
        <h2>Снимался в:
            <ul>
                {% for movie in actor.movie_set.all %}
                    <li><a href="{{ movie.get_url }}">{{ movie }}</a></li>
                {% endfor %}
            </ul>
    </div>
{% endblock %}

movie_project/movie_app/templates/movie_app/actors.html
{% extends 'base.html' %}

{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'movie_app/css/all_movies.css' %}">
{% endblock %}

{% block title %}
    Актеры
{% endblock %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <ul>
    {% for actor in actors %}
        <li><a href="{{ actor.get_url }}">{{ actor }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

movie_project/movie_app/templates/movie_app/director_info.html
{% extends 'base.html' %}

{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'movie_app/css/detail_info.css' %}">
{% endblock %}

{% block title %}
    Режисеры
{% endblock %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <div class="info">
        <h2>Имя - {{ director.first_name }}</h2>
        <h2>Фамилия - {{ director.last_name }}</h2>
        <h3>Email - {{ director.email }}</h3>
        <h3>Снятые фильмы:
            <ul>
                {% for movie in director.movie_set.all %}
                    <li><a href="{{ movie.get_url }}">{{ movie }}</a></li>
                {% endfor %}
            </ul>
        </h3>
    </div>
{% endblock %}

movie_project/movie_app/templates/movie_app/directors.html
{% extends 'base.html' %}

{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'movie_app/css/all_movies.css' %}">
{% endblock %}

{% block title %}
    Режисеры
{% endblock %}

{% block content %}
    <ul>
    {% for director in directors %}
        <li><a href="{{ director.get_url }}">{{ director.first_name|capfirst }} {{ director.last_name|capfirst }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

movie_project/movie_app/templates/movie_app/movie_info.html
{% extends 'base.html' %}

{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'movie_app/css/detail_info.css' %}">
{% endblock %}

{% block title %}
    Фильм {{ movie.name }}
{% endblock %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <div class="info">
        <h2>Название - {{ movie.name }}</h2>
        <h3>Рейтинг - {{ movie.rating }}</h3>
        <h3>Год выхода - {{ movie.year|default:'Неизвестно' }}</h3>
        <h3>Бюджет - {{ movie.budget }}</h3>
        <h3>Режисер -
            {% if movie.directors %}
                <a href="{{movie.directors.get_url }}">{{ movie.directors }}</a></h3>
            {% else %}
                Неизвестно
            {% endif %}
        <h3>Актеры:
            <ul>
                {% for actor in movie.actors.all %}
                    <li><a href="{{ actor.get_url }}">{{ actor }}</a></li>
                {% endfor %}
            </ul>
        </h3>
    </div>

{% endblock %}

movie_project/movie_app/templates/movie_app/show_all_movie.html
{% extends 'base.html' %}

{% load static %}

{% block css_add %}
    <link rel="stylesheet" href="{% static 'movie_app/css/all_movies.css' %}">
{% endblock %}

{% block title %}
    MAIN
{% endblock %}

{% block content %}
    {% include 'includes/navbar.html' %}
    <h2>Список всех фильмов:</h2>
    <ul class="menu">
        {% for movie in movies %}
            <li><a href="{{ movie.get_url }}">{{ movie.name }} - {{ movie.rating }}</a></li>
        {% endfor %}
    </ul>

    <h3>Всего фильмов: {{ agg.id__count }}</h3>
    <h3>Средний бюджет: {{ agg.budget__avg }}</h3>
    <h3>Максимальный рейтинг: {{ agg.rating__max }}</h3>
    <h3>Минимальный рейтинг: {{ agg.rating__min }}</h3>
{% endblock %}

movie_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% block css_add %} {% endblock %}
</head>
<body>
  {% block content %} {% endblock %}
</body>
</html>